name: Build and Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Premake (via Chocolatey)
        run: choco install --no-progress premake --pre

      - name: Generate Visual Studio project
        run: premake5 vs2019

      - name: Build solution
        run: msbuild UnicornEngine.sln /p:Configuration=Debug_Editor /m

      - name: Run unit tests
        run: ./Binaries/Win64/Tests.exe --gtest_output=xml:TestResults.xml
