name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Premake5
        run: |
          curl -L -o premake.zip https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip
          Expand-Archive premake.zip -DestinationPath ./premake
        shell: pwsh
        
      - name: Add premake to PATH
        run: echo "${{ github.workspace }}\scripts\Premake" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
        
      - name: Generate Visual Studio project files with Premake
        run: Scripts\build.bat
        shell: cmd

      - uses: microsoft/setup-msbuild@v1.1
      - name: Build solution
        run: msbuild "Unicorn Engine.sln" /p:Configuration=Tests /p:Platform=x64-windows /m

      - name: Run unit tests
        run: ./Binaries/Win64/Tests.exe --gtest_output=xml:TestResults.xml

