name: CI Build, Test & Coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test-coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (if any)
        run: |
          choco install --no-progress premake
          # Add other installs if needed

      - name: Generate Visual Studio project files with Premake
        run: premake5 vs2019

      - name: Build solution
        run: msbuild UnicornEngine.sln /p:Configuration=Release /m

      - name: Run unit tests
        run: ./Binaries/Win64/Tests_Debug_Editor.exe --gtest_output=xml:TestResults.xml

      - name: Install OpenCppCoverage
        run: choco install --no-progress opencppcoverage

      - name: Run coverage with OpenCppCoverage
        run: |
          OpenCppCoverage.exe --sources . --exclude-files ".*external.*" -- ./Binaries/Win64/Tests_Debug_Editor.exe

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  # or wherever OpenCppCoverage outputs