name: Archive Merged Branch

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && startsWith(github.event.head_commit.message, 'Merge pull request'))

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to push tags

      - name: Set up Git config
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"

      - name: Determine branch and commit info
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH="${{ github.event.pull_request.head.ref }}"
            SHA="${{ github.event.pull_request.merge_commit_sha }}"
          else
            # Extract branch name from merge commit message
            BRANCH=$(git log -1 --pretty=%B | sed -n 's/.*Merge pull request #[0-9]* from .*\///p')
            SHA=$(git rev-parse HEAD)
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Tag and Push
        run: |
          echo "Tagging archive/${{ steps.vars.outputs.branch }} at ${{ steps.vars.outputs.sha }}"
          git tag archive/${{ steps.vars.outputs.branch }} ${{ steps.vars.outputs.sha }}
          git push origin archive/${{ steps.vars.outputs.branch }}
            