name: Archive Branch Tag

permissions:
  contents: write

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.email "bot@example.com"
          git config user.name "AutoTag Bot"

      - name: Tag and Push
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          git tag archive/${BRANCH_NAME} ${COMMIT_SHA}
          git push origin archive/${BRANCH_NAME}
        shell: bash
            